### ISSUE TITLE
Einsatzkräfte hinzufügen

### ISSUE THREAD

**Issue by rennermichael** [andipunz/bwb-protocol#7]
Rückmeldung aus Rottach:
"habe versucht die Einsatzkräfte( alles Bereitschaftsangehörige) hinzuzufügen. Zweimal hat es funktioniert danach kam die Meldung Person konnte nicht gefunden werden."

**Comment by andipunz** [comment]
Ich schau mir das gleich mal an. Ein Screenshot wäre dann immer hilfreich. Workaround der aktuell funktioniert: als externe Einsatzkraft hinzufügen

**Comment by andipunz** [comment]
Ich konnte das ganze nicht nachstellen. Sollte das Problem weiterhin bestehen, dann bitte Screenshot schicken lassen oder evtl. kurze Bildschirmaufnahme
